<?php

namespace Modules\LocationModule\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Modules\LocationModule\Entities\Country;

class SeedCountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = array(
            array('id' => 1,'code' => 'AF' ,'name_en' => "Afghanistan",'phonecode' => 93,'name_ar' =>"افغانستا" ),
            array('id' => 2,'code' => 'AL' ,'name_en' => "Albania",'phonecode' => 355,'name_ar' =>"Albania"),
            array('id' => 3,'code' => 'DZ' ,'name_en' => "Algeria",'phonecode' => 213,'name_ar' => null),
            array('id' => 4,'code' => 'AS' ,'name_en' => "American Samoa",'phonecode' => 1684,'name_ar' => null),
            array('id' => 5,'code' => 'AD' ,'name_en' => "Andorra",'phonecode' => 376,'name_ar' => null),
            array('id' => 6,'code' => 'AO' ,'name_en' => "Angola",'phonecode' => 244,'name_ar' => null),
            array('id' => 7,'code' => 'AI' ,'name_en' => "Anguilla",'phonecode' => 1264,'name_ar' => null),
            array('id' => 8,'code' => 'AQ' ,'name_en' => "Antarctica",'phonecode' => 0,'name_ar' => null),
            array('id' => 9,'code' => 'AG' ,'name_en' => "Antigua And Barbuda",'phonecode' => 1268,'name_ar' => null),
            array('id' => 10,'code' => 'AR','name_en' => "Argentina",'phonecode' => 54,'name_ar' => null),
            array('id' => 11,'code' => 'AM','name_en' => "Armenia",'phonecode' => 374,'name_ar' => 'ارمانيا'),
            array('id' => 12,'code' => 'AW','name_en' => "Aruba",'phonecode' => 297,'name_ar' => null),
            array('id' => 13,'code' => 'AU','name_en' => "Australia",'phonecode' => 61,'name_ar' => null),
            array('id' => 14,'code' => 'AT','name_en' => "Austria",'phonecode' => 43,'name_ar' => null),
            array('id' => 15,'code' => 'AZ','name_en' => "Azerbaijan",'phonecode' => 994,'name_ar' => null),
            array('id' => 16,'code' => 'BS','name_en' => "Bahamas The",'phonecode' => 1242,'name_ar' => null),
            array('id' => 17,'code' => 'BH','name_en' => "Bahrain",'phonecode' => 973,'name_ar' => null),
            array('id' => 18,'code' => 'BD','name_en' => "Bangladesh",'phonecode' => 880,'name_ar' => null),
            array('id' => 19,'code' => 'BB','name_en' => "Barbados",'phonecode' => 1246,'name_ar' => null),
            array('id' => 20,'code' => 'BY','name_en' => "Belarus",'phonecode' => 375,'name_ar' => null),
            array('id' => 21,'code' => 'BE','name_en' => "Belgium",'phonecode' => 32,'name_ar' => null),
            array('id' => 22,'code' => 'BZ','name_en' => "Belize",'phonecode' => 501,'name_ar' => null),
            array('id' => 23,'code' => 'BJ','name_en' => "Benin",'phonecode' => 229,'name_ar' => null),
            array('id' => 24,'code' => 'BM','name_en' => "Bermuda",'phonecode' => 1441,'name_ar' => null),
            array('id' => 25,'code' => 'BT','name_en' => "Bhutan",'phonecode' => 975,'name_ar' => null),
            array('id' => 26,'code' => 'BO','name_en' => "Bolivia",'phonecode' => 591,'name_ar' => null),
            array('id' => 27,'code' => 'BA','name_en' => "Bosnia and Herzegovina",'phonecode' => 387,'name_ar' => null),
            array('id' => 28,'code' => 'BW','name_en' => "Botswana",'phonecode' => 267,'name_ar' => null),
            array('id' => 29,'code' => 'BV','name_en' => "Bouvet Island",'phonecode' => 0,'name_ar' => null),
            array('id' => 30,'code' => 'BR','name_en' => "Brazil",'phonecode' => 55,'name_ar' => null),
            array('id' => 31,'code' => 'IO','name_en' => "British Indian Ocean Territory",'phonecode' => 246,'name_ar' => null),
            array('id' => 32,'code' => 'BN','name_en' => "Brunei",'phonecode' => 673,'name_ar' => null),
            array('id' => 33,'code' => 'BG','name_en' => "Bulgaria",'phonecode' => 359,'name_ar' => null),
            array('id' => 34,'code' => 'BF','name_en' => "Burkina Faso",'phonecode' => 226,'name_ar' => null),
            array('id' => 35,'code' => 'BI','name_en' => "Burundi",'phonecode' => 257,'name_ar' => null),
            array('id' => 36,'code' => 'KH','name_en' => "Cambodia",'phonecode' => 855,'name_ar' => null),
            array('id' => 37,'code' => 'CM','name_en' => "Cameroon",'phonecode' => 237,'name_ar' => null),
            array('id' => 38,'code' => 'CA','name_en' => "Canada",'phonecode' => 1,'name_ar' => null),
            array('id' => 39,'code' => 'CV','name_en' => "Cape Verde",'phonecode' => 238,'name_ar' => null),
            array('id' => 40,'code' => 'KY','name_en' => "Cayman Islands",'phonecode' => 1345,'name_ar' => null),
            array('id' => 41,'code' => 'CF','name_en' => "Central African Republic",'phonecode' => 236,'name_ar' => null),
            array('id' => 42,'code' => 'TD','name_en' => "Chad",'phonecode' => 235,'name_ar' => null),
            array('id' => 43,'code' => 'CL','name_en' => "Chile",'phonecode' => 56,'name_ar' => null),
            array('id' => 44,'code' => 'CN','name_en' => "China",'phonecode' => 86,'name_ar' => null),
            array('id' => 45,'code' => 'CX','name_en' => "Christmas Island",'phonecode' => 61,'name_ar' => null),
            array('id' => 46,'code' => 'CC','name_en' => "Cocos (Keeling,'name_ar' => null) Islands",'phonecode' => 672,'name_ar' => null),
            array('id' => 47,'code' => 'CO','name_en' => "Colombia",'phonecode' => 57,'name_ar' => null),
            array('id' => 48,'code' => 'KM','name_en' => "Comoros",'phonecode' => 269,'name_ar' => null),
            array('id' => 49,'code' => 'CG','name_en' => "Congo",'phonecode' => 242,'name_ar' => null),
            array('id' => 50,'code' => 'CD','name_en' => "Congo The Democratic Republic Of The",'phonecode' => 242,'name_ar' => null),
            array('id' => 51,'code' => 'CK','name_en' => "Cook Islands",'phonecode' => 682,'name_ar' => null),
            array('id' => 52,'code' => 'CR','name_en' => "Costa Rica",'phonecode' => 506,'name_ar' => null),
            array('id' => 53,'code' => 'CI','name_en' => "Cote D Ivoire (Ivory Coast,'name_ar' => null)",'phonecode' => 225,'name_ar' => null),
            array('id' => 54,'code' => 'HR','name_en' => "Croatia (Hrvatska)",'phonecode' => 385,'name_ar' => null),
            array('id' => 55,'code' => 'CU','name_en' => "Cuba",'phonecode' => 53,'name_ar' => null),
            array('id' => 56,'code' => 'CY','name_en' => "Cyprus",'phonecode' => 357,'name_ar' => null),
            array('id' => 57,'code' => 'CZ','name_en' => "Czech Republic",'phonecode' => 420,'name_ar' => null),
            array('id' => 58,'code' => 'DK','name_en' => "Denmark",'phonecode' => 45,'name_ar' => null),
            array('id' => 59,'code' => 'DJ','name_en' => "Djibouti",'phonecode' => 253,'name_ar' => null),
            array('id' => 60,'code' => 'DM','name_en' => "Dominica",'phonecode' => 1767,'name_ar' => null),
            array('id' => 61,'code' => 'DO','name_en' => "Dominican Republic",'phonecode' => 1809,'name_ar' => null),
            array('id' => 62,'code' => 'TP','name_en' => "East Timor",'phonecode' => 670,'name_ar' => null),
            array('id' => 63,'code' => 'EC','name_en' => "Ecuador",'phonecode' => 593,'name_ar' => null),
            array('id' => 64,'code' => 'EG','name_en' => "Egypt",'phonecode' => 20,'name_ar' => 'مصر'),
            array('id' => 65,'code' => 'SV','name_en' => "El Salvador",'phonecode' => 503,'name_ar' => null),
            array('id' => 66,'code' => 'GQ','name_en' => "Equatorial Guinea",'phonecode' => 240,'name_ar' => null),
            array('id' => 67,'code' => 'ER','name_en' => "Eritrea",'phonecode' => 291,'name_ar' => null),
            array('id' => 68,'code' => 'EE','name_en' => "Estonia",'phonecode' => 372,'name_ar' => null),
            array('id' => 69,'code' => 'ET','name_en' => "Ethiopia",'phonecode' => 251,'name_ar' => null),
            array('id' => 70,'code' => 'XA','name_en' => "External Territories of Australia",'phonecode' => 61,'name_ar' => null),
            array('id' => 71,'code' => 'FK','name_en' => "Falkland Islands",'phonecode' => 500,'name_ar' => null),
            array('id' => 72,'code' => 'FO','name_en' => "Faroe Islands",'phonecode' => 298,'name_ar' => null),
            array('id' => 73,'code' => 'FJ','name_en' => "Fiji Islands",'phonecode' => 679,'name_ar' => null),
            array('id' => 74,'code' => 'FI','name_en' => "Finland",'phonecode' => 358,'name_ar' => null),
            array('id' => 75,'code' => 'FR','name_en' => "France",'phonecode' => 33,'name_ar' => 'فرنسا'),
            array('id' => 76,'code' => 'GF','name_en' => "French Guiana",'phonecode' => 594,'name_ar' => null),
            array('id' => 77,'code' => 'PF','name_en' => "French Polynesia",'phonecode' => 689,'name_ar' => null),
            array('id' => 78,'code' => 'TF','name_en' => "French Southern Territories",'phonecode' => 0,'name_ar' => null),
            array('id' => 79,'code' => 'GA','name_en' => "Gabon",'phonecode' => 241,'name_ar' => null),
            array('id' => 80,'code' => 'GM','name_en' => "Gambia The",'phonecode' => 220,'name_ar' => null),
            array('id' => 81,'code' => 'GE','name_en' => "Georgia",'phonecode' => 995,'name_ar' => null),
            array('id' => 82,'code' => 'DE','name_en' => "Germany",'phonecode' => 49,'name_ar' => null),
            array('id' => 83,'code' => 'GH','name_en' => "Ghana",'phonecode' => 233,'name_ar' => null),
            array('id' => 84,'code' => 'GI','name_en' => "Gibraltar",'phonecode' => 350,'name_ar' => null),
            array('id' => 85,'code' => 'GR','name_en' => "Greece",'phonecode' => 30,'name_ar' => null),
            array('id' => 86,'code' => 'GL','name_en' => "Greenland",'phonecode' => 299,'name_ar' => null),
            array('id' => 87,'code' => 'GD','name_en' => "Grenada",'phonecode' => 1473,'name_ar' => null),
            array('id' => 88,'code' => 'GP','name_en' => "Guadeloupe",'phonecode' => 590,'name_ar' => null),
            array('id' => 89,'code' => 'GU','name_en' => "Guam",'phonecode' => 1671,'name_ar' => null),
            array('id' => 90,'code' => 'GT','name_en' => "Guatemala",'phonecode' => 502,'name_ar' => null),
            array('id' => 91,'code' => 'XU','name_en' => "Guernsey and Alderney",'phonecode' => 44,'name_ar' => null),
            array('id' => 92,'code' => 'GN','name_en' => "Guinea",'phonecode' => 224,'name_ar' => null),
            array('id' => 93,'code' => 'GW','name_en' => "Guinea-Bissau",'phonecode' => 245,'name_ar' => null),
            array('id' => 94,'code' => 'GY','name_en' => "Guyana",'phonecode' => 592,'name_ar' => null),
            array('id' => 95,'code' => 'HT','name_en' => "Haiti",'phonecode' => 509,'name_ar' => null),
            array('id' => 96,'code' => 'HM','name_en' => "Heard and McDonald Islands",'phonecode' => 0,'name_ar' => null),
            array('id' => 97,'code' => 'HN','name_en' => "Honduras",'phonecode' => 504,'name_ar' => null),
            array('id' => 98,'code' => 'HK','name_en' => "Hong Kong S.A.R.",'phonecode' => 852,'name_ar' => null),
            array('id' => 99,'code' => 'HU','name_en' => "Hungary",'phonecode' => 36,'name_ar' => null),
            array('id' => 100,'code' => 'IS','name_en' => "Iceland",'phonecode' => 354,'name_ar' => null),
            array('id' => 101,'code' => 'IN','name_en' => "India",'phonecode' => 91,'name_ar' => 'الهند'),
            array('id' => 102,'code' => 'ID','name_en' => "Indonesia",'phonecode' => 62,'name_ar' => 'اندونيسيا'),
            array('id' => 103,'code' => 'IR','name_en' => "Iran",'phonecode' => 98,'name_ar' => null),
            array('id' => 104,'code' => 'IQ','name_en' => "Iraq",'phonecode' => 964,'name_ar' => null),
            array('id' => 105,'code' => 'IE','name_en' => "Ireland",'phonecode' => 353,'name_ar' => null),
            array('id' => 106,'code' => 'IL','name_en' => "Israel",'phonecode' => 972,'name_ar' => null),
            array('id' => 107,'code' => 'IT','name_en' => "Italy",'phonecode' => 39,'name_ar' => null),
            array('id' => 108,'code' => 'JM','name_en' => "Jamaica",'phonecode' => 1876,'name_ar' => null),
            array('id' => 109,'code' => 'JP','name_en' => "Japan",'phonecode' => 81,'name_ar' => null),
            array('id' => 110,'code' => 'XJ','name_en' => "Jersey",'phonecode' => 44,'name_ar' => null),
            array('id' => 111,'code' => 'JO','name_en' => "Jordan",'phonecode' => 962,'name_ar' => null),
            array('id' => 112,'code' => 'KZ','name_en' => "Kazakhstan",'phonecode' => 7,'name_ar' => null),
            array('id' => 113,'code' => 'KE','name_en' => "Kenya",'phonecode' => 254,'name_ar' => null),
            array('id' => 114,'code' => 'KI','name_en' => "Kiribati",'phonecode' => 686,'name_ar' => null),
            array('id' => 115,'code' => 'KP','name_en' => "Korea North",'phonecode' => 850,'name_ar' => null),
            array('id' => 116,'code' => 'KR','name_en' => "Korea South",'phonecode' => 82,'name_ar' => null),
            array('id' => 117,'code' => 'KW','name_en' => "Kuwait",'phonecode' => 965,'name_ar' => null),
            array('id' => 118,'code' => 'KG','name_en' => "Kyrgyzstan",'phonecode' => 996,'name_ar' => null),
            array('id' => 119,'code' => 'LA','name_en' => "Laos",'phonecode' => 856,'name_ar' => null),
            array('id' => 120,'code' => 'LV','name_en' => "Latvia",'phonecode' => 371,'name_ar' => null),
            array('id' => 121,'code' => 'LB','name_en' => "Lebanon",'phonecode' => 961,'name_ar' => null),
            array('id' => 122,'code' => 'LS','name_en' => "Lesotho",'phonecode' => 266,'name_ar' => null),
            array('id' => 123,'code' => 'LR','name_en' => "Liberia",'phonecode' => 231,'name_ar' => null),
            array('id' => 124,'code' => 'LY','name_en' => "Libya",'phonecode' => 218,'name_ar' => null),
            array('id' => 125,'code' => 'LI','name_en' => "Liechtenstein",'phonecode' => 423,'name_ar' => null),
            array('id' => 126,'code' => 'LT','name_en' => "Lithuania",'phonecode' => 370,'name_ar' => null),
            array('id' => 127,'code' => 'LU','name_en' => "Luxembourg",'phonecode' => 352,'name_ar' => null),
            array('id' => 128,'code' => 'MO','name_en' => "Macau S.A.R.",'phonecode' => 853,'name_ar' => null),
            array('id' => 129,'code' => 'MK','name_en' => "Macedonia",'phonecode' => 389,'name_ar' => null),
            array('id' => 130,'code' => 'MG','name_en' => "Madagascar",'phonecode' => 261,'name_ar' => null),
            array('id' => 131,'code' => 'MW','name_en' => "Malawi",'phonecode' => 265,'name_ar' => null),
            array('id' => 132,'code' => 'MY','name_en' => "Malaysia",'phonecode' => 60,'name_ar' => null),
            array('id' => 133,'code' => 'MV','name_en' => "Maldives",'phonecode' => 960,'name_ar' => null),
            array('id' => 134,'code' => 'ML','name_en' => "Mali",'phonecode' => 223,'name_ar' => null),
            array('id' => 135,'code' => 'MT','name_en' => "Malta",'phonecode' => 356,'name_ar' => null),
            array('id' => 136,'code' => 'XM','name_en' => "Man (Isle of)",'phonecode' => 44,'name_ar' => null),
            array('id' => 137,'code' => 'MH','name_en' => "Marshall Islands",'phonecode' => 692,'name_ar' => null),
            array('id' => 138,'code' => 'MQ','name_en' => "Martinique",'phonecode' => 596,'name_ar' => null),
            array('id' => 139,'code' => 'MR','name_en' => "Mauritania",'phonecode' => 222,'name_ar' => null),
            array('id' => 140,'code' => 'MU','name_en' => "Mauritius",'phonecode' => 230,'name_ar' => null),
            array('id' => 141,'code' => 'YT','name_en' => "Mayotte",'phonecode' => 269,'name_ar' => null),
            array('id' => 142,'code' => 'MX','name_en' => "Mexico",'phonecode' => 52,'name_ar' => null),
            array('id' => 143,'code' => 'FM','name_en' => "Micronesia",'phonecode' => 691,'name_ar' => null),
            array('id' => 144,'code' => 'MD','name_en' => "Moldova",'phonecode' => 373,'name_ar' => null),
            array('id' => 145,'code' => 'MC','name_en' => "Monaco",'phonecode' => 377,'name_ar' => null),
            array('id' => 146,'code' => 'MN','name_en' => "Mongolia",'phonecode' => 976,'name_ar' => null),
            array('id' => 147,'code' => 'MS','name_en' => "Montserrat",'phonecode' => 1664,'name_ar' => null),
            array('id' => 148,'code' => 'MA','name_en' => "Morocco",'phonecode' => 212,'name_ar' => null),
            array('id' => 149,'code' => 'MZ','name_en' => "Mozambique",'phonecode' => 258,'name_ar' => null),
            array('id' => 150,'code' => 'MM','name_en' => "Myanmar",'phonecode' => 95,'name_ar' => null),
            array('id' => 151,'code' => 'NA','name_en' => "Namibia",'phonecode' => 264,'name_ar' => null),
            array('id' => 152,'code' => 'NR','name_en' => "Nauru",'phonecode' => 674,'name_ar' => null),
            array('id' => 153,'code' => 'NP','name_en' => "Nepal",'phonecode' => 977,'name_ar' => null),
            array('id' => 154,'code' => 'AN','name_en' => "Netherlands Antilles",'phonecode' => 599,'name_ar' => null),
            array('id' => 155,'code' => 'NL','name_en' => "Netherlands The",'phonecode' => 31,'name_ar' => null),
            array('id' => 156,'code' => 'NC','name_en' => "New Caledonia",'phonecode' => 687,'name_ar' => null),
            array('id' => 157,'code' => 'NZ','name_en' => "New Zealand",'phonecode' => 64,'name_ar' => null),
            array('id' => 158,'code' => 'NI','name_en' => "Nicaragua",'phonecode' => 505,'name_ar' => null),
            array('id' => 159,'code' => 'NE','name_en' => "Niger",'phonecode' => 227,'name_ar' => null),
            array('id' => 160,'code' => 'NG','name_en' => "Nigeria",'phonecode' => 234,'name_ar' => null),
            array('id' => 161,'code' => 'NU','name_en' => "Niue",'phonecode' => 683,'name_ar' => null),
            array('id' => 162,'code' => 'NF','name_en' => "Norfolk Island",'phonecode' => 672,'name_ar' => null),
            array('id' => 163,'code' => 'MP','name_en' => "Northern Mariana Islands",'phonecode' => 1670,'name_ar' => null),
            array('id' => 164,'code' => 'NO','name_en' => "Norway",'phonecode' => 47,'name_ar' => null),
            array('id' => 165,'code' => 'OM','name_en' => "Oman",'phonecode' => 968,'name_ar' => null),
            array('id' => 166,'code' => 'PK','name_en' => "Pakistan",'phonecode' => 92,'name_ar' => null),
            array('id' => 167,'code' => 'PW','name_en' => "Palau",'phonecode' => 680,'name_ar' => null),
            array('id' => 168,'code' => 'PS','name_en' => "Palestinian Territory Occupied",'phonecode' => 970,'name_ar' => null),
            array('id' => 169,'code' => 'PA','name_en' => "Panama",'phonecode' => 507,'name_ar' => null),
            array('id' => 170,'code' => 'PG','name_en' => "Papua new Guinea",'phonecode' => 675,'name_ar' => null),
            array('id' => 171,'code' => 'PY','name_en' => "Paraguay",'phonecode' => 595,'name_ar' => null),
            array('id' => 172,'code' => 'PE','name_en' => "Peru",'phonecode' => 51,'name_ar' => null),
            array('id' => 173,'code' => 'PH','name_en' => "Philippines",'phonecode' => 63,'name_ar' => null),
            array('id' => 174,'code' => 'PN','name_en' => "Pitcairn Island",'phonecode' => 0,'name_ar' => null),
            array('id' => 175,'code' => 'PL','name_en' => "Poland",'phonecode' => 48,'name_ar' => null),
            array('id' => 176,'code' => 'PT','name_en' => "Portugal",'phonecode' => 351,'name_ar' => null),
            array('id' => 177,'code' => 'PR','name_en' => "Puerto Rico",'phonecode' => 1787,'name_ar' => null),
            array('id' => 178,'code' => 'QA','name_en' => "Qatar",'phonecode' => 974,'name_ar' => null),
            array('id' => 179,'code' => 'RE','name_en' => "Reunion",'phonecode' => 262,'name_ar' => null),
            array('id' => 180,'code' => 'RO','name_en' => "Romania",'phonecode' => 40,'name_ar' => null),
            array('id' => 181,'code' => 'RU','name_en' => "Russia",'phonecode' => 70,'name_ar' => null),
            array('id' => 182,'code' => 'RW','name_en' => "Rwanda",'phonecode' => 250,'name_ar' => null),
            array('id' => 183,'code' => 'SH','name_en' => "Saint Helena",'phonecode' => 290,'name_ar' => null),
            array('id' => 184,'code' => 'KN','name_en' => "Saint Kitts And Nevis",'phonecode' => 1869,'name_ar' => null),
            array('id' => 185,'code' => 'LC','name_en' => "Saint Lucia",'phonecode' => 1758,'name_ar' => null),
            array('id' => 186,'code' => 'PM','name_en' => "Saint Pierre and Miquelon",'phonecode' => 508,'name_ar' => null),
            array('id' => 187,'code' => 'VC','name_en' => "Saint Vincent And The Grenadines",'phonecode' => 1784,'name_ar' => null),
            array('id' => 188,'code' => 'WS','name_en' => "Samoa",'phonecode' => 684,'name_ar' => null),
            array('id' => 189,'code' => 'SM','name_en' => "San Marino",'phonecode' => 378,'name_ar' => null),
            array('id' => 190,'code' => 'ST','name_en' => "Sao Tome and Principe",'phonecode' => 239,'name_ar' => null),
            array('id' => 191,'code' => 'SA','name_en' => "Saudi Arabia",'phonecode' => 966,'name_ar' => null),
            array('id' => 192,'code' => 'SN','name_en' => "Senegal",'phonecode' => 221,'name_ar' => null),
            array('id' => 193,'code' => 'RS','name_en' => "Serbia",'phonecode' => 381,'name_ar' => null),
            array('id' => 194,'code' => 'SC','name_en' => "Seychelles",'phonecode' => 248,'name_ar' => null),
            array('id' => 195,'code' => 'SL','name_en' => "Sierra Leone",'phonecode' => 232,'name_ar' => null),
            array('id' => 196,'code' => 'SG','name_en' => "Singapore",'phonecode' => 65,'name_ar' => null),
            array('id' => 197,'code' => 'SK','name_en' => "Slovakia",'phonecode' => 421,'name_ar' => null),
            array('id' => 198,'code' => 'SI','name_en' => "Slovenia",'phonecode' => 386,'name_ar' => null),
            array('id' => 199,'code' => 'XG','name_en' => "Smaller Territories of the UK",'phonecode' => 44,'name_ar' => null),
            array('id' => 200,'code' => 'SB','name_en' => "Solomon Islands",'phonecode' => 677,'name_ar' => null),
            array('id' => 201,'code' => 'SO','name_en' => "Somalia",'phonecode' => 252,'name_ar' => null),
            array('id' => 202,'code' => 'ZA','name_en' => "South Africa",'phonecode' => 27,'name_ar' => null),
            array('id' => 203,'code' => 'GS','name_en' => "South Georgia",'phonecode' => 0,'name_ar' => null),
            array('id' => 204,'code' => 'SS','name_en' => "South Sudan",'phonecode' => 211,'name_ar' => null),
            array('id' => 205,'code' => 'ES','name_en' => "Spain",'phonecode' => 34,'name_ar' => null),
            array('id' => 206,'code' => 'LK','name_en' => "Sri Lanka",'phonecode' => 94,'name_ar' => null),
            array('id' => 207,'code' => 'SD','name_en' => "Sudan",'phonecode' => 249,'name_ar' => null),
            array('id' => 208,'code' => 'SR','name_en' => "Suriname_en",'phonecode' => 597,'name_ar' => null),
            array('id' => 209,'code' => 'SJ','name_en' => "Svalbard And Jan Mayen Islands",'phonecode' => 47,'name_ar' => null),
            array('id' => 210,'code' => 'SZ','name_en' => "Swaziland",'phonecode' => 268,'name_ar' => null),
            array('id' => 211,'code' => 'SE','name_en' => "Sweden",'phonecode' => 46,'name_ar' => null),
            array('id' => 212,'code' => 'CH','name_en' => "Switzerland",'phonecode' => 41,'name_ar' => null),
            array('id' => 213,'code' => 'SY','name_en' => "Syria",'phonecode' => 963,'name_ar' => null),
            array('id' => 214,'code' => 'TW','name_en' => "Taiwan",'phonecode' => 886,'name_ar' => null),
            array('id' => 215,'code' => 'TJ','name_en' => "Tajikistan",'phonecode' => 992,'name_ar' => null),
            array('id' => 216,'code' => 'TZ','name_en' => "Tanzania",'phonecode' => 255,'name_ar' => null),
            array('id' => 217,'code' => 'TH','name_en' => "Thailand",'phonecode' => 66,'name_ar' => null),
            array('id' => 218,'code' => 'TG','name_en' => "Togo",'phonecode' => 228,'name_ar' => null),
            array('id' => 219,'code' => 'TK','name_en' => "Tokelau",'phonecode' => 690,'name_ar' => null),
            array('id' => 220,'code' => 'TO','name_en' => "Tonga",'phonecode' => 676,'name_ar' => null),
            array('id' => 221,'code' => 'TT','name_en' => "Trinidad And Tobago",'phonecode' => 1868,'name_ar' => null),
            array('id' => 222,'code' => 'TN','name_en' => "Tunisia",'phonecode' => 216,'name_ar' => null),
            array('id' => 223,'code' => 'TR','name_en' => "Turkey",'phonecode' => 90,'name_ar' => null),
            array('id' => 224,'code' => 'TM','name_en' => "Turkmenistan",'phonecode' => 7370,'name_ar' => null),
            array('id' => 225,'code' => 'TC','name_en' => "Turks And Caicos Islands",'phonecode' => 1649,'name_ar' => null),
            array('id' => 226,'code' => 'TV','name_en' => "Tuvalu",'phonecode' => 688,'name_ar' => null),
            array('id' => 227,'code' => 'UG','name_en' => "Uganda",'phonecode' => 256,'name_ar' => null),
            array('id' => 228,'code' => 'UA','name_en' => "Ukraine",'phonecode' => 380,'name_ar' => null),
            array('id' => 229,'code' => 'AE','name_en' => "United Arab Emirates",'phonecode' => 971,'name_ar' => null),
            array('id' => 230,'code' => 'GB','name_en' => "United Kingdom",'phonecode' => 44,'name_ar' => null),
            array('id' => 231,'code' => 'US','name_en' => "United States",'phonecode' => 1,'name_ar' => null),
            array('id' => 232,'code' => 'UM','name_en' => "United States Minor Outlying Islands",'phonecode' => 1,'name_ar' => null),
            array('id' => 233,'code' => 'UY','name_en' => "Uruguay",'phonecode' => 598,'name_ar' => null),
            array('id' => 234,'code' => 'UZ','name_en' => "Uzbekistan",'phonecode' => 998,'name_ar' => null),
            array('id' => 235,'code' => 'VU','name_en' => "Vanuatu",'phonecode' => 678,'name_ar' => null),
            array('id' => 236,'code' => 'VA','name_en' => "Vatican City State (Holy See,'name_ar' => null)",'phonecode' => 39,'name_ar' => null),
            array('id' => 237,'code' => 'VE','name_en' => "Venezuela",'phonecode' => 58,'name_ar' => null),
            array('id' => 238,'code' => 'VN','name_en' => "Vietnam",'phonecode' => 84,'name_ar' => null),
            array('id' => 239,'code' => 'VG','name_en' => "Virgin Islands (British,'name_ar' => null)",'phonecode' => 1284,'name_ar' => null),
            array('id' => 240,'code' => 'VI','name_en' => "Virgin Islands (US,'name_ar' => null)",'phonecode' => 1340,'name_ar' => null),
            array('id' => 241,'code' => 'WF','name_en' => "Wallis And Futuna Islands",'phonecode' => 681,'name_ar' => null),
            array('id' => 242,'code' => 'EH','name_en' => "Western Sahara",'phonecode' => 212,'name_ar' => null),
            array('id' => 243,'code' => 'YE','name_en' => "Yemen",'phonecode' => 967,'name_ar' => null),
            array('id' => 244,'code' => 'YU','name_en' => "Yugoslavia",'phonecode' => 38,'name_ar' => null),
            array('id' => 245,'code' => 'ZM','name_en' => "Zambia",'phonecode' => 260,'name_ar' => null),
            array('id' => 246,'code' => 'ZW','name_en' => "Zimbabwe",'phonecode' => 263,'name_ar' => null),
        );
        Country::insert($countries);
            }
}
